### ISSUE TITLE
essa aqui complicou

### ISSUE THREAD

**Issue by mafefreeitas** [ProfRonan/fizz-buzz-mafefreeitas#2]
professor, a atividade do fizzbuzz eu fiz há muito tempo e o bot deu o "vezinho" verde de confirmação, então achei que tinha dado certo :( Sem pelo menos essa atividade, eu ficaria faltando 0,2 pontos pra passar na cadeira contando com 100 no resto das atividades. o Senhor pode me deixar refazer? ou me ajudar a refazer na quarta-feira, por favor 🙏🏼 @SeuRonao

**Comment by SeuRonao** [comment]
Na realidade, essa estava correta mesmo.
